package reviewprepared

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/planwerk/planwerk-review/internal/attribution"
)

// Column widths for the findings summary table. Matched to the gapanalysis
// renderer so users moving between commands see a consistent layout.
const (
	colFeature  = 10
	colCategory = 22
	colTitle    = 56
	colPointer  = 28
)

// render switches between Markdown and JSON output. Pattern lifted from
// gapanalysis.render so behavior stays consistent across commands.
func render(w io.Writer, result *Result, version, format string) error {
	switch format {
	case "json":
		return RenderJSON(w, result)
	default:
		RenderMarkdown(w, result, version)
		return nil
	}
}

// RenderJSON emits the result as pretty-printed JSON. ImprovedJSON is omitted
// from the JSON output unless the caller requested PR creation — but since
// the runner has already populated/cleared it appropriately, we just emit
// what we have.
func RenderJSON(w io.Writer, result *Result) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// RenderMarkdown renders the review as a Markdown report: header, per-feature
// summary, and full finding details grouped by feature.
func RenderMarkdown(w io.Writer, result *Result, version string) {
	if result == nil {
		_, _ = fmt.Fprintln(w, "# Review Prepared\n\n_no result_")
		return
	}

	totalFindings := 0
	for _, fr := range result.Features {
		totalFindings += len(fr.Findings)
	}

	_, _ = fmt.Fprintf(w, "# Review Prepared: %s\n\n", result.RepoFullName)
	if version != "" {
		_, _ = fmt.Fprintf(w, "_Generated by %s_\n\n", attribution.ToolWithVersion(version))
	}
	_, _ = fmt.Fprintf(w, "Reviewed **%d** prepared feature(s) — found **%d** finding(s).\n\n",
		len(result.Features), totalFindings)

	if result.Overview != "" {
		_, _ = fmt.Fprintf(w, "## Overview\n\n%s\n\n", strings.TrimSpace(result.Overview))
	}

	if totalFindings == 0 {
		_, _ = fmt.Fprintln(w, "All prepared features look good. No findings to report.")
		return
	}

	printFindingsTable(w, result)

	for _, fr := range result.Features {
		if len(fr.Findings) == 0 {
			continue
		}
		_, _ = fmt.Fprintf(w, "## %s — %s\n\n", fr.FeatureID, fr.Title)
		if fr.Summary != "" {
			_, _ = fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(fr.Summary))
		}
		for _, f := range fr.Findings {
			renderFindingDetails(w, f)
		}
	}
}

func printFindingsTable(w io.Writer, result *Result) {
	_, _ = fmt.Fprintf(w, "## Findings Overview\n\n")
	_, _ = fmt.Fprintf(w, "| #  | ID     | Severity | Feature    | Category               | Title                                                    | Spec pointer                 |\n")
	_, _ = fmt.Fprintf(w, "|----|--------|----------|------------|------------------------|----------------------------------------------------------|------------------------------|\n")
	n := 0
	for _, fr := range result.Features {
		for _, f := range fr.Findings {
			n++
			_, _ = fmt.Fprintf(w, "| %2d | %-6s | %-8s | %-*s | %-*s | %-*s | %-*s |\n",
				n,
				f.ID,
				f.Severity,
				colFeature, truncate(fr.FeatureID, colFeature),
				colCategory, truncate(string(f.Category), colCategory),
				colTitle, truncate(f.Title, colTitle),
				colPointer, truncate(singleLine(f.SpecPointer), colPointer),
			)
		}
	}
	_, _ = fmt.Fprintln(w)
}

func renderFindingDetails(w io.Writer, f Finding) {
	_, _ = fmt.Fprintf(w, "### %s — %s\n\n", f.ID, f.Title)
	_, _ = fmt.Fprintf(w, "- **Severity**: %s\n", f.Severity)
	_, _ = fmt.Fprintf(w, "- **Category**: %s\n", f.Category)
	if f.Confidence != "" {
		_, _ = fmt.Fprintf(w, "- **Confidence**: %s\n", f.Confidence)
	}
	_, _ = fmt.Fprintf(w, "- **Feature**: %s (`%s`)\n", f.FeatureID, f.FeatureFile)
	if f.SpecPointer != "" {
		_, _ = fmt.Fprintf(w, "- **Spec pointer**: `%s`\n", f.SpecPointer)
	}
	_, _ = fmt.Fprintln(w)
	if f.Description != "" {
		_, _ = fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(f.Description))
	}
	if f.Suggestion != "" {
		_, _ = fmt.Fprintf(w, "**Suggested fix**: %s\n\n", strings.TrimSpace(f.Suggestion))
	}
}

func singleLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return strings.TrimSpace(s)
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	if maxLen < 3 {
		return s[:maxLen]
	}
	return s[:maxLen-3] + "..."
}
