package meta

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"

	"github.com/planwerk/planwerk-review/internal/attribution"
)

// RenderJSON writes the meta split result as indented JSON.
func RenderJSON(w io.Writer, result *Result) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// RenderMarkdown writes a preview of the meta split: a heading naming the Meta
// Issue and the Sub Issue count, a generated-by line, one block per Sub Issue
// (title, scope, status, and a Description preview), and the synced Meta body.
// On a dry run the Sub Issues have no number yet, so each block reports it as
// planned and the Meta body still carries its {{sub:KEY}} placeholders.
func RenderMarkdown(w io.Writer, repoFullName string, metaNumber int, version string, result *Result) {
	_, _ = fmt.Fprintf(w, "# Meta split: %s#%d — %d sub-issue(s)\n\n", repoFullName, metaNumber, len(result.SubIssues))
	_, _ = fmt.Fprintf(w, "> Generated by planwerk-review %s %s\n\n", version, attribution.Assistant())
	_, _ = fmt.Fprint(w, "---\n\n")

	if len(result.SubIssues) == 0 {
		_, _ = fmt.Fprint(w, "No work packages found in the meta issue; nothing was filed.\n")
		return
	}

	for i, s := range result.SubIssues {
		scope := strings.TrimSpace(s.Scope)
		if scope == "" {
			scope = "Medium"
		}
		_, _ = fmt.Fprintf(w, "## %d. %s\n\n", i+1, strings.TrimSpace(s.Title))
		_, _ = fmt.Fprintf(w, "- Scope: %s\n", scope)
		_, _ = fmt.Fprintf(w, "- Status: %s\n", subIssueStatus(s))
		_, _ = fmt.Fprintln(w)
		if d := strings.TrimSpace(s.Description); d != "" {
			_, _ = fmt.Fprintf(w, "%s\n\n", d)
		}
	}

	_, _ = fmt.Fprint(w, "---\n\n## Meta issue body\n\n")
	body := strings.TrimRight(result.MetaBody, "\n")
	_, _ = fmt.Fprintf(w, "%s\n", body)
}

// subIssueStatus describes where a Sub Issue stands: planned (dry run, not yet
// filed), created and linked, created but unlinked, or created with a recorded
// link failure.
func subIssueStatus(s SubIssue) string {
	if s.Number == 0 {
		return "planned (not filed)"
	}
	switch {
	case s.Linked:
		return fmt.Sprintf("created %s, linked", s.URL)
	case s.LinkError != "":
		return fmt.Sprintf("created %s, link failed: %s", s.URL, s.LinkError)
	default:
		return fmt.Sprintf("created %s, not linked", s.URL)
	}
}
