package gapanalysis

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/planwerk/planwerk-review/internal/github"
)

// Column widths for the gaps summary table. Same look-and-feel as the audit
// summary so users moving between commands recognize the format.
const (
	colFeature  = 10
	colType     = 18
	colTitle    = 56
	colEvidence = 38
)

// render switches between Markdown and JSON output and triggers the
// interactive issue creation flow when --create-issues is set. It is the
// single entry point used by the runner.
func render(w io.Writer, result *Result, repo *github.Repo, opts Options) error {
	switch opts.Format {
	case "json":
		return RenderJSON(w, result)
	default:
		RenderMarkdown(w, result, opts.Version)
	}

	if opts.CreateIssues {
		return RunInteractiveIssueCreation(w, result, repo.Owner, repo.Name)
	}
	return nil
}

// RenderJSON emits the result as pretty-printed JSON.
func RenderJSON(w io.Writer, result *Result) error {
	enc := json.NewEncoder(w)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// RenderMarkdown renders the gap-analysis as a Markdown report: header,
// per-feature summary table, and full gap details grouped by feature.
func RenderMarkdown(w io.Writer, result *Result, version string) {
	if result == nil {
		_, _ = fmt.Fprintln(w, "# Gap Analysis\n\n_no result_")
		return
	}

	totalGaps := 0
	for _, fg := range result.Features {
		totalGaps += len(fg.Gaps)
	}

	_, _ = fmt.Fprintf(w, "# Gap Analysis: %s\n\n", result.RepoFullName)
	if version != "" {
		_, _ = fmt.Fprintf(w, "_Generated by planwerk-review %s_\n\n", version)
	}
	_, _ = fmt.Fprintf(w, "Analyzed **%d** completed feature(s) — found **%d** gap(s).\n\n",
		len(result.Features), totalGaps)

	if result.Overview != "" {
		_, _ = fmt.Fprintf(w, "## Overview\n\n%s\n\n", strings.TrimSpace(result.Overview))
	}

	if totalGaps == 0 {
		_, _ = fmt.Fprintln(w, "All completed features appear fully implemented. No gaps to report.")
		return
	}

	printGapTable(w, result)

	for _, fg := range result.Features {
		if len(fg.Gaps) == 0 {
			continue
		}
		_, _ = fmt.Fprintf(w, "## %s — %s\n\n", fg.FeatureID, fg.Title)
		if fg.Summary != "" {
			_, _ = fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(fg.Summary))
		}
		for _, g := range fg.Gaps {
			renderGapDetails(w, g)
		}
	}
}

func printGapTable(w io.Writer, result *Result) {
	_, _ = fmt.Fprintf(w, "## Gaps Overview\n\n")
	_, _ = fmt.Fprintf(w, "| #  | ID     | Severity | Feature    | Type               | Title                                                    | Evidence                               |\n")
	_, _ = fmt.Fprintf(w, "|----|--------|----------|------------|--------------------|----------------------------------------------------------|----------------------------------------|\n")
	n := 0
	for _, fg := range result.Features {
		for _, g := range fg.Gaps {
			n++
			_, _ = fmt.Fprintf(w, "| %2d | %-6s | %-8s | %-*s | %-*s | %-*s | %-*s |\n",
				n,
				g.ID,
				g.Severity,
				colFeature, truncate(fg.FeatureID, colFeature),
				colType, truncate(string(g.Type), colType),
				colTitle, truncate(g.Title, colTitle),
				colEvidence, truncate(singleLine(g.Evidence), colEvidence),
			)
		}
	}
	_, _ = fmt.Fprintln(w)
}

func renderGapDetails(w io.Writer, g Gap) {
	_, _ = fmt.Fprintf(w, "### %s — %s\n\n", g.ID, g.Title)
	_, _ = fmt.Fprintf(w, "- **Severity**: %s\n", g.Severity)
	_, _ = fmt.Fprintf(w, "- **Type**: %s\n", g.Type)
	if g.Confidence != "" {
		_, _ = fmt.Fprintf(w, "- **Confidence**: %s\n", g.Confidence)
	}
	_, _ = fmt.Fprintf(w, "- **Feature**: %s (`%s`)\n", g.FeatureID, g.FeatureFile)
	_, _ = fmt.Fprintln(w)
	if g.Source != "" {
		_, _ = fmt.Fprintf(w, "**From spec**: %s\n\n", strings.TrimSpace(g.Source))
	}
	if g.Description != "" {
		_, _ = fmt.Fprintf(w, "%s\n\n", strings.TrimSpace(g.Description))
	}
	if g.Evidence != "" {
		_, _ = fmt.Fprintf(w, "**Evidence**: %s\n\n", strings.TrimSpace(g.Evidence))
	}
	if g.Suggested.Title != "" {
		_, _ = fmt.Fprintf(w, "**Suggested issue title**: %s\n\n", g.Suggested.Title)
	}
}

// RunInteractiveIssueCreation walks each gap, shows its detail block, and
// asks whether to create a GitHub issue. Reuses github.RunInteractiveIssueCreation
// so the y/N/q prompt and duplicate-search behavior match audit and propose.
func RunInteractiveIssueCreation(w io.Writer, result *Result, owner, name string) error {
	gaps := result.AllGaps()
	if len(gaps) == 0 {
		_, _ = fmt.Fprintln(w, "\nNo gaps to create issues for.")
		return nil
	}

	candidates := make([]github.IssueCandidate, 0, len(gaps))
	for _, g := range gaps {
		title := g.Suggested.Title
		if title == "" {
			title = g.Title
		}
		body := g.Suggested.Body
		if body == "" {
			body = buildIssueBody(g)
		}
		preview := buildIssuePreview(g)
		candidates = append(candidates, github.IssueCandidate{
			Title:   title,
			Preview: preview,
			Body:    body,
		})
	}

	return github.RunInteractiveIssueCreation(
		w, os.Stdin, candidates, owner, name, "gap",
		github.CreateIssue, github.SearchIssues,
	)
}

// buildIssuePreview produces the on-screen block shown before each y/N prompt.
func buildIssuePreview(g Gap) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "Gap: %s\n", g.Title)
	fmt.Fprintf(&b, "  ID:        %s\n", g.ID)
	fmt.Fprintf(&b, "  Severity:  %s\n", g.Severity)
	fmt.Fprintf(&b, "  Type:      %s\n", g.Type)
	fmt.Fprintf(&b, "  Feature:   %s (%s)\n", g.FeatureID, g.FeatureFile)
	if g.Confidence != "" {
		fmt.Fprintf(&b, "  Confidence: %s\n", g.Confidence)
	}
	if g.Source != "" {
		fmt.Fprintf(&b, "\nFrom spec:\n  %s\n", indent(strings.TrimSpace(g.Source), "  "))
	}
	if g.Description != "" {
		fmt.Fprintf(&b, "\nDescription:\n  %s\n", indent(strings.TrimSpace(g.Description), "  "))
	}
	if g.Evidence != "" {
		fmt.Fprintf(&b, "\nEvidence:\n  %s\n", indent(strings.TrimSpace(g.Evidence), "  "))
	}
	return b.String()
}

// buildIssueBody is the fallback issue body when Claude did not provide one.
func buildIssueBody(g Gap) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "**Severity**: %s | **Type**: %s | **Feature**: %s\n\n", g.Severity, g.Type, g.FeatureID)
	if g.Source != "" {
		fmt.Fprintf(&b, "## From the Planwerk spec\n\n%s\n\n", strings.TrimSpace(g.Source))
	}
	if g.Description != "" {
		fmt.Fprintf(&b, "## Gap\n\n%s\n\n", strings.TrimSpace(g.Description))
	}
	if g.Evidence != "" {
		fmt.Fprintf(&b, "## Evidence\n\n%s\n\n", strings.TrimSpace(g.Evidence))
	}
	if g.Confidence != "" {
		fmt.Fprintf(&b, "**Confidence**: %s\n\n", g.Confidence)
	}
	fmt.Fprintf(&b, "_Source: `.planwerk/completed/%s`_\n\n", g.FeatureFile)
	fmt.Fprint(&b, "---\n\n_Generated by [planwerk-review](https://github.com/planwerk/planwerk-review) gap-analysis with Claude Code_\n")
	return b.String()
}

func indent(s, prefix string) string {
	if s == "" {
		return ""
	}
	lines := strings.Split(s, "\n")
	for i, l := range lines {
		if i == 0 {
			continue
		}
		lines[i] = prefix + l
	}
	return strings.Join(lines, "\n")
}

func singleLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return strings.TrimSpace(s)
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	if maxLen < 3 {
		return s[:maxLen]
	}
	return s[:maxLen-3] + "..."
}
