package elaborate

import (
	"fmt"
	"io"
	"strings"
)

// RenderMarkdown writes the elaborated issue body as Markdown to w.
func RenderMarkdown(w io.Writer, repoFullName string, issueNumber int, version string, r *Result) {
	_, _ = fmt.Fprintf(w, "# Elaboration: %s#%d — %s\n\n", repoFullName, issueNumber, r.Title)
	_, _ = fmt.Fprintf(w, "> Generated by planwerk-review %s with Claude Code\n\n", version)
	_, _ = fmt.Fprint(w, "---\n\n")
	_, _ = fmt.Fprint(w, r.Body)
	if !strings.HasSuffix(r.Body, "\n") {
		_, _ = fmt.Fprintln(w)
	}
}

// BuildIssueBody renders the canonical issue body for the elaboration.
// Section headers and ordering match the example issue style
// (plexsphere/plexsphere#10): Description, Motivation, Affected Areas,
// Acceptance Criteria, Non-Goals, References, plus a generated-by footer.
//
// Description and Motivation are emitted verbatim — Claude is responsible
// for the prose density and depth. List sections are normalised so the
// output stays consistent regardless of how the model returns them.
func BuildIssueBody(r *Result) string {
	var b strings.Builder

	if d := strings.TrimSpace(r.Description); d != "" {
		fmt.Fprint(&b, "**Description:**\n\n")
		fmt.Fprintln(&b, d)
		fmt.Fprintln(&b)
	}

	if m := strings.TrimSpace(r.Motivation); m != "" {
		fmt.Fprint(&b, "**Motivation:**\n\n")
		fmt.Fprintln(&b, m)
		fmt.Fprintln(&b)
	}

	if len(r.AffectedAreas) > 0 {
		fmt.Fprint(&b, "**Affected Areas:**\n\n")
		for _, a := range r.AffectedAreas {
			a = strings.TrimSpace(a)
			if a == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", a)
		}
		fmt.Fprintln(&b)
	}

	if len(r.AcceptanceCriteria) > 0 {
		fmt.Fprint(&b, "**Acceptance Criteria:**\n\n")
		for _, ac := range r.AcceptanceCriteria {
			ac = strings.TrimSpace(ac)
			if ac == "" {
				continue
			}
			fmt.Fprintf(&b, "- [ ] %s\n", ac)
		}
		fmt.Fprintln(&b)
	}

	if len(r.NonGoals) > 0 {
		fmt.Fprint(&b, "**Non-Goals:**\n\n")
		for _, n := range r.NonGoals {
			n = strings.TrimSpace(n)
			if n == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", n)
		}
		fmt.Fprintln(&b)
	}

	if len(r.References) > 0 {
		fmt.Fprint(&b, "**References:**\n\n")
		for _, ref := range r.References {
			ref = strings.TrimSpace(ref)
			if ref == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", ref)
		}
		fmt.Fprintln(&b)
	}

	fmt.Fprint(&b, "---\n\n_Elaborated by [planwerk-review](https://github.com/planwerk/planwerk-review) with Claude Code_\n")
	return b.String()
}
