package elaborate

import (
	"fmt"
	"io"
	"strings"

	"github.com/planwerk/planwerk-agent/internal/attribution"
)

// RenderMarkdown writes the elaborated issue body as Markdown to w.
func RenderMarkdown(w io.Writer, repoFullName string, issueNumber int, version string, r *Result) {
	_, _ = fmt.Fprintf(w, "# Elaboration: %s#%d — %s\n\n", repoFullName, issueNumber, r.Title)
	_, _ = fmt.Fprintf(w, "> Generated by %s %s\n\n", attribution.ToolWithVersion(version), attribution.AssistantWith(r.Model))
	_, _ = fmt.Fprint(w, "---\n\n")
	_, _ = fmt.Fprint(w, r.Body)
	if !strings.HasSuffix(r.Body, "\n") {
		_, _ = fmt.Fprintln(w)
	}
}

// BuildIssueBody renders the canonical issue body for the elaboration.
// Section headers and ordering match the example issue style
// (plexsphere/plexsphere#10): Description, Motivation, an optional User
// Stories section, Affected Areas, Acceptance Criteria, Non-Goals,
// References, plus a generated-by footer.
//
// Description and Motivation are emitted verbatim — Claude is responsible
// for the prose density and depth. List sections are normalised so the
// output stays consistent regardless of how the model returns them.
func BuildIssueBody(r *Result) string {
	var b strings.Builder

	if d := strings.TrimSpace(r.Description); d != "" {
		fmt.Fprint(&b, "**Description:**\n\n")
		fmt.Fprintln(&b, d)
		fmt.Fprintln(&b)
	}

	if m := strings.TrimSpace(r.Motivation); m != "" {
		fmt.Fprint(&b, "**Motivation:**\n\n")
		fmt.Fprintln(&b, m)
		fmt.Fprintln(&b)
	}

	if len(r.UserStories) > 0 {
		var stories strings.Builder
		for _, s := range r.UserStories {
			role := strings.TrimSpace(s.Role)
			want := strings.TrimSpace(s.Want)
			soThat := strings.TrimSpace(s.SoThat)
			if role == "" && want == "" && soThat == "" {
				continue
			}
			fmt.Fprintf(&stories, "- As a %s, I want %s, so that %s\n", role, want, soThat)
			for _, c := range s.Criteria {
				c = strings.TrimSpace(c)
				if c == "" {
					continue
				}
				fmt.Fprintf(&stories, "  - %s\n", c)
			}
		}
		if stories.Len() > 0 {
			fmt.Fprint(&b, "**User Stories:**\n\n")
			b.WriteString(stories.String())
			fmt.Fprintln(&b)
		}
	}

	if len(r.AffectedAreas) > 0 {
		fmt.Fprint(&b, "**Affected Areas:**\n\n")
		for _, a := range r.AffectedAreas {
			a = strings.TrimSpace(a)
			if a == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", a)
		}
		fmt.Fprintln(&b)
	}

	if len(r.AcceptanceCriteria) > 0 {
		fmt.Fprint(&b, "**Acceptance Criteria:**\n\n")
		for _, ac := range r.AcceptanceCriteria {
			ac = strings.TrimSpace(ac)
			if ac == "" {
				continue
			}
			fmt.Fprintf(&b, "- [ ] %s\n", ac)
		}
		fmt.Fprintln(&b)
	}

	if len(r.NonGoals) > 0 {
		fmt.Fprint(&b, "**Non-Goals:**\n\n")
		for _, n := range r.NonGoals {
			n = strings.TrimSpace(n)
			if n == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", n)
		}
		fmt.Fprintln(&b)
	}

	if len(r.References) > 0 {
		fmt.Fprint(&b, "**References:**\n\n")
		for _, ref := range r.References {
			ref = strings.TrimSpace(ref)
			if ref == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", ref)
		}
		fmt.Fprintln(&b)
	}

	if r.ReviewScore != nil {
		fmt.Fprintf(&b, "**Executability score:** %d/10\n\n", *r.ReviewScore)
	}

	if len(r.UnresolvedGaps) > 0 {
		fmt.Fprint(&b, "**Reviewer Notes (unresolved):**\n\n")
		fmt.Fprint(&b, "The reviewer pass scored this plan below the executability bar. The refine loop could not close these gaps. Address them before implementing:\n\n")
		for _, g := range r.UnresolvedGaps {
			g = strings.TrimSpace(g)
			if g == "" {
				continue
			}
			fmt.Fprintf(&b, "- %s\n", g)
		}
		fmt.Fprintln(&b)
		if t := strings.TrimSpace(r.ReviewTarget); t != "" {
			fmt.Fprintf(&b, "What a 10/10 plan would look like: %s\n\n", t)
		}
	}

	fmt.Fprintf(&b, "---\n\n_Elaborated by %s %s_\n", attribution.Tool(), attribution.AssistantWith(r.Model))
	return b.String()
}
