package propose

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/planwerk/planwerk-review/internal/github"
)

// titleColumnWidth is the fixed width of the Title column in the proposals
// summary table.
const titleColumnWidth = 58

// RunInteractiveIssueCreation displays all proposals in a summary table,
// then walks through each one, showing full content and asking whether to
// create a GitHub issue.
func RunInteractiveIssueCreation(w io.Writer, result *ProposalResult, owner, name string) error {
	cp := CategorizeByPriority(result.Proposals)

	// 1. Show summary table
	printSummaryTable(w, cp)

	// 2. Build candidates list, walking proposals by priority
	ordered := make([]Proposal, 0, len(result.Proposals))
	ordered = append(ordered, cp.High...)
	ordered = append(ordered, cp.Medium...)
	ordered = append(ordered, cp.Low...)

	candidates := make([]github.IssueCandidate, 0, len(ordered))
	for _, p := range ordered {
		var previewBuf bytes.Buffer
		r := NewRenderer(&previewBuf)
		r.renderProposal(p)

		candidates = append(candidates, github.IssueCandidate{
			Title:   p.Title,
			Preview: previewBuf.String(),
			Body:    buildIssueBody(p),
		})
	}

	return github.RunInteractiveIssueCreation(
		w, os.Stdin, candidates, owner, name, "proposal",
		github.CreateIssue, github.SearchIssues,
	)
}

func printSummaryTable(w io.Writer, cp CategorizedProposals) {
	total := len(cp.High) + len(cp.Medium) + len(cp.Low)
	_, _ = fmt.Fprintf(w, "\n## Proposals Overview (%d total)\n\n", total)
	_, _ = fmt.Fprintf(w, "| # | ID     | Priority | Category       | Scope  | Title                                                      |\n")
	_, _ = fmt.Fprintf(w, "|---|--------|----------|----------------|--------|------------------------------------------------------------|\n")

	n := 0
	for _, p := range cp.High {
		n++
		_, _ = fmt.Fprintf(w, "| %d | %s | %-8s | %-14s | %-6s | %-*s |\n", n, p.ID, p.Priority, p.Category, p.Scope, titleColumnWidth, truncate(p.Title, titleColumnWidth))
	}
	for _, p := range cp.Medium {
		n++
		_, _ = fmt.Fprintf(w, "| %d | %s | %-8s | %-14s | %-6s | %-*s |\n", n, p.ID, p.Priority, p.Category, p.Scope, titleColumnWidth, truncate(p.Title, titleColumnWidth))
	}
	for _, p := range cp.Low {
		n++
		_, _ = fmt.Fprintf(w, "| %d | %s | %-8s | %-14s | %-6s | %-*s |\n", n, p.ID, p.Priority, p.Category, p.Scope, titleColumnWidth, truncate(p.Title, titleColumnWidth))
	}
	_, _ = fmt.Fprintln(w)
}

func buildIssueBody(p Proposal) string {
	var b strings.Builder

	fmt.Fprintf(&b, "**Category**: %s | **Scope**: %s | **Priority**: %s\n\n", p.Category, p.Scope, p.Priority)
	fmt.Fprintf(&b, "## Description\n\n%s\n\n", p.Description)
	fmt.Fprintf(&b, "## Motivation\n\n%s\n\n", p.Motivation)

	if len(p.AffectedAreas) > 0 {
		fmt.Fprint(&b, "## Affected Areas\n\n")
		for _, area := range p.AffectedAreas {
			fmt.Fprintf(&b, "- `%s`\n", area)
		}
		fmt.Fprintln(&b)
	}

	if len(p.AcceptanceCriteria) > 0 {
		fmt.Fprint(&b, "## Acceptance Criteria\n\n")
		for _, ac := range p.AcceptanceCriteria {
			fmt.Fprintf(&b, "- [ ] %s\n", ac)
		}
		fmt.Fprintln(&b)
	}

	fmt.Fprint(&b, "---\n\n_Generated by [planwerk-review](https://github.com/planwerk/planwerk-review) with Claude CLI_\n")

	return b.String()
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}
