package propose

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
)

// Renderer handles output of proposal results.
type Renderer struct {
	w io.Writer
}

// NewRenderer creates a Renderer that writes to w.
func NewRenderer(w io.Writer) *Renderer {
	return &Renderer{w: w}
}

// RenderMarkdown writes the proposal result as structured Markdown.
func (r *Renderer) RenderMarkdown(result ProposalResult, repoFullName, version string) {
	_, _ = fmt.Fprintf(r.w, "# Feature Proposals: %s\n\n", repoFullName)
	_, _ = fmt.Fprintf(r.w, "> Generated by planwerk-review %s with Claude Code\n\n", version)

	// Repository overview
	_, _ = fmt.Fprint(r.w, "## Repository Overview\n\n")
	_, _ = fmt.Fprintf(r.w, "%s\n\n", result.RepositoryOverview)
	_, _ = fmt.Fprint(r.w, "---\n\n")

	cp := CategorizeByPriority(result.Proposals)

	r.renderPrioritySection("HIGH Priority", cp.High)
	r.renderPrioritySection("MEDIUM Priority", cp.Medium)
	r.renderPrioritySection("LOW Priority", cp.Low)

	r.renderSummary(cp)
}

// RenderJSON writes the proposal result as formatted JSON.
func (r *Renderer) RenderJSON(result ProposalResult) error {
	enc := json.NewEncoder(r.w)
	enc.SetIndent("", "  ")
	return enc.Encode(result)
}

// RenderIssues writes each proposal as a standalone Markdown issue template, ready to copy-paste into GitHub issues.
func (r *Renderer) RenderIssues(result ProposalResult, repoFullName string) {
	_, _ = fmt.Fprintf(r.w, "# Feature Proposals: %s\n\n", repoFullName)
	_, _ = fmt.Fprintf(r.w, "Below are %d feature proposals, each formatted as a GitHub issue.\n\n", len(result.Proposals))

	for i, p := range result.Proposals {
		if i > 0 {
			_, _ = fmt.Fprint(r.w, "\n---\n\n")
		}
		r.renderIssue(p)
	}
}

func (r *Renderer) renderPrioritySection(label string, proposals []Proposal) {
	_, _ = fmt.Fprintf(r.w, "## %s (%d)\n\n", label, len(proposals))
	if len(proposals) == 0 {
		_, _ = fmt.Fprint(r.w, "No proposals.\n\n")
		_, _ = fmt.Fprint(r.w, "---\n\n")
		return
	}
	for _, p := range proposals {
		r.renderProposal(p)
	}
	_, _ = fmt.Fprint(r.w, "---\n\n")
}

func (r *Renderer) renderProposal(p Proposal) {
	_, _ = fmt.Fprintf(r.w, "### %s: %s\n\n", p.ID, p.Title)
	_, _ = fmt.Fprintf(r.w, "**Category**: %s | **Scope**: %s\n\n", p.Category, p.Scope)
	_, _ = fmt.Fprintf(r.w, "**Description**: %s\n\n", p.Description)
	_, _ = fmt.Fprintf(r.w, "**Motivation**: %s\n\n", p.Motivation)

	if len(p.AffectedAreas) > 0 {
		_, _ = fmt.Fprint(r.w, "**Affected Areas**:\n")
		for _, area := range p.AffectedAreas {
			_, _ = fmt.Fprintf(r.w, "- `%s`\n", area)
		}
		_, _ = fmt.Fprintln(r.w)
	}

	if len(p.AcceptanceCriteria) > 0 {
		_, _ = fmt.Fprint(r.w, "**Acceptance Criteria**:\n")
		for _, ac := range p.AcceptanceCriteria {
			_, _ = fmt.Fprintf(r.w, "- [ ] %s\n", ac)
		}
		_, _ = fmt.Fprintln(r.w)
	}
}

func (r *Renderer) renderIssue(p Proposal) {
	_, _ = fmt.Fprintf(r.w, "## %s\n\n", p.Title)

	// Priority is surfaced in the body, not as part of the title or a
	// tag-like label.
	_, _ = fmt.Fprintf(r.w, "**Priority**: %s | **Category**: %s | **Scope**: %s\n\n", p.Priority, p.Category, p.Scope)

	labels := []string{p.Category, "scope:" + strings.ToLower(p.Scope)}
	_, _ = fmt.Fprintf(r.w, "**Labels**: %s\n\n", strings.Join(labels, ", "))

	_, _ = fmt.Fprint(r.w, "### Description\n\n")
	_, _ = fmt.Fprintf(r.w, "%s\n\n", p.Description)

	_, _ = fmt.Fprint(r.w, "### Motivation\n\n")
	_, _ = fmt.Fprintf(r.w, "%s\n\n", p.Motivation)

	if len(p.AffectedAreas) > 0 {
		_, _ = fmt.Fprint(r.w, "### Affected Areas\n\n")
		for _, area := range p.AffectedAreas {
			_, _ = fmt.Fprintf(r.w, "- `%s`\n", area)
		}
		_, _ = fmt.Fprintln(r.w)
	}

	if len(p.AcceptanceCriteria) > 0 {
		_, _ = fmt.Fprint(r.w, "### Acceptance Criteria\n\n")
		for _, ac := range p.AcceptanceCriteria {
			_, _ = fmt.Fprintf(r.w, "- [ ] %s\n", ac)
		}
		_, _ = fmt.Fprintln(r.w)
	}
}

func (r *Renderer) renderSummary(cp CategorizedProposals) {
	total := len(cp.High) + len(cp.Medium) + len(cp.Low)
	_, _ = fmt.Fprint(r.w, "## Summary\n\n")
	_, _ = fmt.Fprintf(r.w, "**Total Proposals**: %d\n\n", total)
	_, _ = fmt.Fprintln(r.w, "| Priority | Count |")
	_, _ = fmt.Fprintln(r.w, "|----------|-------|")
	_, _ = fmt.Fprintf(r.w, "| HIGH     | %-5d |\n", len(cp.High))
	_, _ = fmt.Fprintf(r.w, "| MEDIUM   | %-5d |\n", len(cp.Medium))
	_, _ = fmt.Fprintf(r.w, "| LOW      | %-5d |\n", len(cp.Low))
}
