package prompt

import (
	"fmt"
	"io"
	"strings"

	"github.com/planwerk/planwerk-review/internal/github"
)

// Options configures the prompt pipeline.
type Options struct {
	IssueRef string
	Mode     Mode
	Version  string
}

// Mode selects the variant of prompt to emit. Audit issues benefit from the
// "fix" variant (apply the suggested fix, run tests, open a PR); proposal
// issues benefit from the "implement" variant (design + implement +
// document).
type Mode int

const (
	// ModeAuto picks ModeFix when the issue body carries the audit
	// severity marker ("**Severity**:"), and ModeImplement otherwise.
	ModeAuto Mode = iota
	// ModeFix asks the agent to apply the audit finding's suggested fix.
	ModeFix
	// ModeImplement asks the agent to design and implement the proposed feature.
	ModeImplement
)

// Runner builds and writes a copy-paste-ready Claude Code prompt for a
// given GitHub issue. No Claude call is involved — the runner is a
// deterministic prompt assembler so the output is stable, testable, and
// safe to pipe into other tools.
type Runner struct {
	GitHub GitHubClient
}

// NewRunner returns a Runner wired with the production GitHub backend.
func NewRunner() *Runner {
	return &Runner{GitHub: defaultGitHubClient{}}
}

// Run is a package-level convenience that delegates to NewRunner().Run.
func Run(w io.Writer, opts Options) error {
	return NewRunner().Run(w, opts)
}

// Run fetches the issue, picks (or honors) the prompt mode, and writes the
// rendered prompt to w.
func (r *Runner) Run(w io.Writer, opts Options) error {
	owner, name, number, err := github.ParseIssueRef(opts.IssueRef)
	if err != nil {
		return fmt.Errorf("parsing issue ref: %w", err)
	}
	issue, err := r.GitHub.GetIssue(owner, name, number)
	if err != nil {
		return fmt.Errorf("fetching issue: %w", err)
	}

	mode := opts.Mode
	if mode == ModeAuto {
		mode = inferMode(issue)
	}

	body := Build(issue, mode, opts.Version)
	_, err = io.WriteString(w, body)
	return err
}

// Build renders the prompt body for the given issue and mode. Exposed so
// tests and callers that already have an *Issue can render without going
// through the gh CLI.
func Build(issue *github.Issue, mode Mode, version string) string {
	if mode == ModeAuto {
		mode = inferMode(issue)
	}
	var sb strings.Builder

	fmt.Fprintf(&sb, "<!-- planwerk-review prompt %s for %s/%s#%d -->\n\n",
		modeName(mode), issue.Owner, issue.Name, issue.Number)

	switch mode {
	case ModeFix:
		writeFixHeader(&sb)
	case ModeImplement:
		writeImplementHeader(&sb)
	}

	fmt.Fprintf(&sb, "## Source Issue\n\n")
	fmt.Fprintf(&sb, "**Repository**: %s/%s\n", issue.Owner, issue.Name)
	fmt.Fprintf(&sb, "**Issue**: #%d — %s\n", issue.Number, issue.Title)
	if issue.URL != "" {
		fmt.Fprintf(&sb, "**URL**: %s\n", issue.URL)
	}
	if issue.State != "" {
		fmt.Fprintf(&sb, "**State**: %s\n", issue.State)
	}
	sb.WriteString("\n### Issue Body\n\n")
	sb.WriteString(strings.TrimSpace(issue.Body))
	sb.WriteString("\n\n")

	switch mode {
	case ModeFix:
		writeFixFooter(&sb, issue)
	case ModeImplement:
		writeImplementFooter(&sb, issue)
	}

	if version != "" {
		fmt.Fprintf(&sb, "\n---\n\n_Prompt generated by planwerk-review %s_\n", version)
	}

	return sb.String()
}

func modeName(m Mode) string {
	switch m {
	case ModeFix:
		return "fix"
	case ModeImplement:
		return "implement"
	default:
		return "auto"
	}
}

func writeFixHeader(sb *strings.Builder) {
	sb.WriteString(`You are a senior engineer fixing a finding raised by planwerk-review's audit. Apply the suggested fix faithfully — do not enlarge the scope.

Workflow:

1. Read the issue body below in full. Note the file paths, line numbers, code snippets, and suggested fix it cites.
2. Open every cited file and confirm the cited code still exists at (or near) the cited line. If the code has moved or changed, locate it before editing.
3. Apply the suggested fix. If the issue lists multiple occurrences, fix all of them. If the suggested fix is a description (not literal replacement code), translate it into the smallest possible code change that satisfies the description without expanding scope.
4. Run the project's test suite for the affected packages. If a test fails because the fix changed observable behavior, update the test only when the new behavior is correct per the issue; never weaken a test to make it pass.
5. Add or extend tests that cover the bug being fixed when none exists. Match the project's existing test conventions (file layout, table-driven vs. case-per-function, helper naming).
6. Update documentation (README, CHANGELOG, doc comments) when the fix changes behavior described in docs.
7. Commit with a message that references the issue number ("Fixes #N: <short title>"). Open a draft PR linked to the issue.

Rules:
- Stay within the scope of the issue. Do NOT refactor adjacent code, rename symbols, or "clean up" surrounding files.
- Do NOT skip pre-commit hooks or test suites with --no-verify.
- If the suggested fix conflicts with a stronger invariant in the code, stop and write the conflict into a comment on the issue instead of guessing.

`)
}

func writeFixFooter(sb *strings.Builder, _ *github.Issue) {
	sb.WriteString("## Action\n\n")
	sb.WriteString("Apply the fix described above, run the tests, update docs if needed, and open a draft PR. When done, summarise the change set and any deviations from the suggested fix in a single comment on the issue.\n")
}

func writeImplementHeader(sb *strings.Builder) {
	sb.WriteString(`You are a senior engineer implementing a feature described by an existing GitHub issue. The issue may be a high-level proposal or a fully elaborated engineering plan — read it in full before touching code.

Workflow:

1. Read the issue body below. If the issue has Acceptance Criteria, treat them as the definition of done.
2. Walk the relevant parts of the repository to confirm the issue's claims about existing files, packages, and conventions. Where the issue cites a file, verify the file still exists and matches the description.
3. Plan the smallest change set that satisfies every Acceptance Criterion. Stage the work as a sequence of small, reviewable commits — do not produce a single monolithic diff.
4. Implement the changes:
   - Match the project's existing layout, naming, and test conventions.
   - Add unit tests for new logic; add integration / E2E tests when the project has them for comparable features.
   - Add or update documentation (README, CHANGELOG, doc comments) for every user-facing change, CLI flag, or public API.
5. Run the project's test suite (and lint/vet). Fix the root cause of any failure — do not skip hooks or weaken assertions.
6. Open a draft PR linked to the issue. The PR description should walk a reviewer through the change set and call out anything that diverged from the issue.

Rules:
- If the issue's Non-Goals list excludes something, do NOT do it. Stay inside the agreed scope.
- If you discover the issue is wrong (a cited file does not exist, an Acceptance Criterion is unreachable), stop and post a clarifying comment on the issue instead of inventing scope.
- Do NOT skip pre-commit hooks or test suites with --no-verify.

`)
}

func writeImplementFooter(sb *strings.Builder, _ *github.Issue) {
	sb.WriteString("## Action\n\n")
	sb.WriteString("Implement the issue end-to-end (code + tests + docs), keep commits reviewable, and open a draft PR linked to the issue. Summarise the work and any scope deviations in a comment on the issue.\n")
}

// inferMode picks ModeFix for issues whose body carries the audit severity
// marker ("**Severity**:") and ModeImplement otherwise. Audit-generated
// issues always include that marker in the body (see
// audit.renderGroupMarkdown), so this gives the right default in practice
// without requiring the user to know which subcommand produced the issue.
func inferMode(issue *github.Issue) Mode {
	if strings.Contains(issue.Body, "**Severity**:") {
		return ModeFix
	}
	return ModeImplement
}
