package audit

import (
	"bytes"
	"strings"
	"testing"

	"github.com/planwerk/planwerk-review/internal/report"
)

func TestBuildGroupTitle_SingleOccurrence(t *testing.T) {
	g := FindingGroup{
		Pattern:     "err-wrap",
		File:        "internal/foo/bar.go",
		MaxSeverity: report.SeverityWarning,
		Findings: []report.Finding{
			{Title: "Missing error wrap", File: "internal/foo/bar.go", Line: 42, Severity: report.SeverityWarning},
		},
	}
	got := buildGroupTitle(g)
	want := "Missing error wrap (internal/foo/bar.go:42)"
	if got != want {
		t.Errorf("title = %q, want %q", got, want)
	}
}

func TestBuildGroupTitle_SingleOccurrence_NoLine(t *testing.T) {
	g := FindingGroup{
		Pattern:     "p",
		File:        "a.go",
		MaxSeverity: report.SeverityInfo,
		Findings: []report.Finding{
			{Title: "Something", File: "a.go", Severity: report.SeverityInfo},
		},
	}
	got := buildGroupTitle(g)
	if !strings.Contains(got, "(a.go)") {
		t.Errorf("title without line should use file only: %q", got)
	}
	if strings.Contains(got, ":0") {
		t.Errorf("title must not contain ':0' line suffix: %q", got)
	}
}

func TestBuildGroupTitle_MultipleOccurrences(t *testing.T) {
	g := FindingGroup{
		Pattern:     "err-wrap",
		File:        "internal/foo/bar.go",
		MaxSeverity: report.SeverityCritical,
		Findings: []report.Finding{
			{File: "internal/foo/bar.go", Line: 10, Severity: report.SeverityCritical},
			{File: "internal/foo/bar.go", Line: 20, Severity: report.SeverityCritical},
			{File: "internal/foo/bar.go", Line: 30, Severity: report.SeverityCritical},
		},
	}
	got := buildGroupTitle(g)
	want := "err-wrap: internal/foo/bar.go (3 occurrences)"
	if got != want {
		t.Errorf("title = %q, want %q", got, want)
	}
}

func TestBuildGroupBody_ContainsAllOccurrences(t *testing.T) {
	g := FindingGroup{
		Pattern:     "err-wrap",
		File:        "a.go",
		MaxSeverity: report.SeverityWarning,
		Findings: []report.Finding{
			{File: "a.go", Line: 10, Severity: report.SeverityWarning, Problem: "first problem", Action: "fix first"},
			{File: "a.go", Line: 20, Severity: report.SeverityWarning, Problem: "second problem", Action: "fix second"},
		},
	}
	body := buildGroupBody(g)
	for _, want := range []string{
		"**Severity**: WARNING",
		"**File**: `a.go` (2 occurrences)",
		"## Occurrences",
		"### Line 10",
		"### Line 20",
		"first problem",
		"second problem",
		"fix first",
		"fix second",
		"planwerk-review",
	} {
		if !strings.Contains(body, want) {
			t.Errorf("body missing %q\nfull body:\n%s", want, body)
		}
	}
}

func TestBuildGroupPreview_NoFooter(t *testing.T) {
	g := FindingGroup{
		Pattern: "p", File: "a.go", MaxSeverity: report.SeverityInfo,
		Findings: []report.Finding{{File: "a.go", Line: 1, Severity: report.SeverityInfo, Problem: "x", Action: "y"}},
	}
	preview := buildGroupPreview(g)
	if strings.Contains(preview, "Generated by") {
		t.Errorf("preview must not contain footer:\n%s", preview)
	}
}

func TestRunInteractiveIssueCreation_EmptyGroups(t *testing.T) {
	result := &report.ReviewResult{
		Findings: []report.Finding{
			{Severity: report.SeverityInfo, File: "a.go", Line: 1, Title: "t"},
		},
	}

	var buf bytes.Buffer
	err := RunInteractiveIssueCreation(&buf, strings.NewReader(""), result, "o", "r", report.SeverityBlocking)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	out := buf.String()
	if !strings.Contains(out, "No findings at or above severity BLOCKING") {
		t.Errorf("expected friendly empty message, got: %s", out)
	}
}

func TestRunInteractiveIssueCreation_EmptyResult(t *testing.T) {
	result := &report.ReviewResult{Findings: nil}
	var buf bytes.Buffer
	err := RunInteractiveIssueCreation(&buf, strings.NewReader(""), result, "o", "r", report.SeverityInfo)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !strings.Contains(buf.String(), "No findings") {
		t.Errorf("expected friendly empty message, got: %s", buf.String())
	}
}
