package audit

import (
	"bytes"
	"fmt"
	"io"
	"strings"

	"github.com/planwerk/planwerk-review/internal/github"
	"github.com/planwerk/planwerk-review/internal/report"
)

// Column widths for the findings summary table.
const (
	patternColumnWidth = 30
	fileColumnWidth    = 44
)

// RunInteractiveIssueCreation groups findings, filters them by minSeverity,
// and walks through each resulting group to interactively create a GitHub
// issue via the shared github helper.
func RunInteractiveIssueCreation(
	w io.Writer,
	in io.Reader,
	result *report.ReviewResult,
	owner, name string,
	minSeverity report.Severity,
) error {
	groups := FilterBySeverity(GroupFindings(result.Findings), minSeverity)
	if len(groups) == 0 {
		_, _ = fmt.Fprintf(w, "\nNo findings at or above severity %s — no issues to create.\n", minSeverity)
		return nil
	}

	printFindingsSummaryTable(w, groups)

	candidates := make([]github.IssueCandidate, 0, len(groups))
	for _, g := range groups {
		candidates = append(candidates, github.IssueCandidate{
			Title:   buildGroupTitle(g),
			Preview: buildGroupPreview(g),
			Body:    buildGroupBody(g),
		})
	}

	return github.RunInteractiveIssueCreation(
		w, in, candidates, owner, name, "finding",
		github.CreateIssue, github.SearchIssues,
	)
}

func printFindingsSummaryTable(w io.Writer, groups []FindingGroup) {
	_, _ = fmt.Fprintf(w, "\n## Findings Overview (%d group(s))\n\n", len(groups))
	_, _ = fmt.Fprintf(w, "| # | Severity | Count | Pattern                        | File                                         |\n")
	_, _ = fmt.Fprintf(w, "|---|----------|-------|--------------------------------|----------------------------------------------|\n")
	for i, g := range groups {
		_, _ = fmt.Fprintf(w, "| %d | %-8s | %-5d | %-*s | %-*s |\n",
			i+1, g.MaxSeverity, len(g.Findings),
			patternColumnWidth, truncateStr(g.Pattern, patternColumnWidth),
			fileColumnWidth, truncateStr(g.File, fileColumnWidth))
	}
	_, _ = fmt.Fprintln(w)
}

// buildGroupTitle returns the title used both on-screen and as the GitHub
// issue title. Single-occurrence groups use the finding's own title; multi-
// occurrence groups summarize the pattern and file with a count.
func buildGroupTitle(g FindingGroup) string {
	if len(g.Findings) == 1 {
		f := g.Findings[0]
		loc := f.File
		if f.Line > 0 {
			loc = fmt.Sprintf("%s:%d", f.File, f.Line)
		}
		title := f.Title
		if title == "" {
			title = g.Pattern
		}
		return fmt.Sprintf("[%s] %s (%s)", g.MaxSeverity, title, loc)
	}
	return fmt.Sprintf("[%s] %s: %s (%d occurrences)", g.MaxSeverity, g.Pattern, g.File, len(g.Findings))
}

func buildGroupPreview(g FindingGroup) string {
	return renderGroupMarkdown(g, false)
}

func buildGroupBody(g FindingGroup) string {
	return renderGroupMarkdown(g, true)
}

// renderGroupMarkdown renders a finding group as Markdown. When withFooter is
// true, a footer is appended for the GitHub issue body.
func renderGroupMarkdown(g FindingGroup, withFooter bool) string {
	var b bytes.Buffer

	fmt.Fprintf(&b, "**Severity**: %s | **Pattern**: `%s`\n\n", g.MaxSeverity, g.Pattern)
	fmt.Fprintf(&b, "**File**: `%s`", g.File)
	if len(g.Findings) > 1 {
		fmt.Fprintf(&b, " (%d occurrences)", len(g.Findings))
	}
	fmt.Fprint(&b, "\n\n")

	if len(g.Findings) == 1 {
		renderFindingDetails(&b, g.Findings[0], false)
	} else {
		fmt.Fprint(&b, "## Occurrences\n\n")
		for _, f := range g.Findings {
			renderFindingDetails(&b, f, true)
		}
	}

	if withFooter {
		fmt.Fprint(&b, "---\n\n_Generated by [planwerk-review](https://github.com/planwerk/planwerk-review) audit with Claude Code_\n")
	}

	return b.String()
}

func renderFindingDetails(b *bytes.Buffer, f report.Finding, withLineHeader bool) {
	if withLineHeader {
		if f.Line > 0 {
			fmt.Fprintf(b, "### Line %d\n\n", f.Line)
		} else {
			fmt.Fprint(b, "### Occurrence\n\n")
		}
	}
	if f.Problem != "" {
		fmt.Fprintf(b, "**Problem**: %s\n\n", f.Problem)
	}
	if f.Action != "" {
		fmt.Fprintf(b, "**Action**: %s\n\n", f.Action)
	}
	if f.CodeSnippet != "" {
		fmt.Fprintf(b, "```\n%s\n```\n\n", strings.TrimRight(f.CodeSnippet, "\n"))
	}
	if f.SuggestedFix != "" {
		fmt.Fprintf(b, "**Suggested fix**:\n\n```\n%s\n```\n\n", strings.TrimRight(f.SuggestedFix, "\n"))
	}
}

func truncateStr(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	if maxLen < 3 {
		return s[:maxLen]
	}
	return s[:maxLen-3] + "..."
}
