package address

import (
	"fmt"
	"io"
	"log/slog"
	"strings"

	"github.com/planwerk/planwerk-review/internal/attribution"
	"github.com/planwerk/planwerk-review/internal/github"
	"github.com/planwerk/planwerk-review/internal/report"
)

// addressCommentFooter attributes the posted address report to planwerk-review,
// naming the model that produced it and matching the footer the fix/rebase
// subcommands append to their PR comments.
func addressCommentFooter() string {
	return "_Address report generated by " + attribution.Link + " address " + attribution.Assistant() + "_"
}

// threadReplyFooter attributes a per-thread reply to planwerk-review, naming the
// model that produced it.
func threadReplyFooter() string {
	return "_Posted by " + attribution.Link + " address " + attribution.Assistant() + "_"
}

// printDryRun lists the threads a real run would address and the planned
// actions, without invoking Claude or committing.
func printDryRun(w io.Writer, fullName string, number int, opts Options, selected []github.ReviewThread) {
	_, _ = fmt.Fprintf(w, "[dry-run] Would address %d thread(s) on %s#%d:\n", len(selected), fullName, number)
	for _, t := range selected {
		_, _ = fmt.Fprintf(w, "  - %s  %s\n", t.ID, threadLocation(t))
		if len(t.Comments) > 0 {
			_, _ = fmt.Fprintf(w, "      %s: %s\n", commentAuthor(t.Comments[0]), oneLineExcerpt(t.Comments[0].Body))
		}
	}
	commitMode := "one commit per thread"
	if !opts.OneCommitPerThread {
		commitMode = "one aggregate commit"
	}
	_, _ = fmt.Fprintf(w, "[dry-run] Planned: %s; reply=%t; resolve=%t; address-comment=%t. No Claude invocation, no commits.\n",
		commitMode, opts.Reply, opts.Resolve, !opts.NoAddressComment)
}

// commentAuthor returns the comment's author login or a placeholder.
func commentAuthor(c github.ReviewThreadComment) string {
	if c.Author == "" {
		return "(unknown)"
	}
	return c.Author
}

// formatThreadReply renders the per-thread reply body: the session's one-line
// summary, the files it touched, and the attribution footer.
func formatThreadReply(t report.AddressedThread) string {
	var b strings.Builder
	summary := strings.TrimSpace(t.Summary)
	if summary == "" {
		summary = "Addressed this review comment in a follow-up commit."
	}
	b.WriteString(summary)
	if len(t.Files) > 0 {
		fmt.Fprintf(&b, "\n\nFiles changed: %s", strings.Join(backtickEach(t.Files), ", "))
	}
	b.WriteString("\n\n---\n\n")
	b.WriteString(threadReplyFooter())
	b.WriteString("\n")
	return b.String()
}

// formatAddressComment renders the aggregate report posted back onto the PR: a
// per-thread breakdown of what changed plus the joined overall summaries.
func formatAddressComment(threads []report.AddressedThread, summaries []string, version string) string {
	var b strings.Builder
	b.WriteString("## Address Report\n\n")
	fmt.Fprintf(&b, "> Addressed by planwerk-review %s %s\n\n", version, attribution.Assistant())
	fmt.Fprintf(&b, "<!-- planwerk-address: threads=%d addressed=%d -->\n\n", len(threads), countAddressed(threads))

	b.WriteString("### Threads\n\n")
	if len(threads) == 0 {
		b.WriteString("No threads were addressed.\n\n")
	}
	for _, t := range threads {
		fmt.Fprintf(&b, "- **%s** — %s: %s\n", t.ThreadID, t.Status, strings.TrimSpace(t.Summary))
		if len(t.Files) > 0 {
			fmt.Fprintf(&b, "  - Files: %s\n", strings.Join(backtickEach(t.Files), ", "))
		}
	}

	if joined := strings.TrimSpace(strings.Join(summaries, "\n\n")); joined != "" {
		b.WriteString("\n### Summary\n\n")
		b.WriteString(joined)
		b.WriteString("\n")
	}

	b.WriteString("\n---\n\n")
	b.WriteString(addressCommentFooter())
	b.WriteString("\n")
	return b.String()
}

// countAddressed totals the threads the session committed (DONE or
// DONE_WITH_CONCERNS), for the machine-readable summary marker.
func countAddressed(threads []report.AddressedThread) int {
	n := 0
	for _, t := range threads {
		if parseStatus(t.Status).addressed() {
			n++
		}
	}
	return n
}

// backtickEach wraps each string in backticks for Markdown inline-code display.
func backtickEach(items []string) []string {
	out := make([]string, len(items))
	for i, s := range items {
		out[i] = "`" + s + "`"
	}
	return out
}

// postAddressComment posts the aggregate report as a fresh PR comment unless
// --no-address-comment is set. Best-effort: a GitHub failure is logged and
// surfaced but never aborts the run — the follow-up commits are already pushed.
func (r *Runner) postAddressComment(w io.Writer, opts Options, owner, repo string, number int, threads []report.AddressedThread, summaries []string) {
	if opts.NoAddressComment {
		return
	}
	if len(threads) == 0 {
		return
	}
	body := formatAddressComment(threads, summaries, opts.Version)
	url, err := r.GitHub.AddPRComment(owner, repo, number, body)
	if err != nil {
		slog.Warn("posting address comment failed", "pr", number, "err", err)
		_, _ = fmt.Fprintf(w, "\nCould not post the address report as a PR comment: %v\n", err)
		return
	}
	slog.Info("posted address report comment", "pr", number, "url", url)
	_, _ = fmt.Fprintf(w, "\nPosted the address report as a comment on PR #%d", number)
	if url != "" {
		_, _ = fmt.Fprintf(w, " (%s)", url)
	}
	_, _ = fmt.Fprintln(w)
}
